### ISSUE TITLE
using pyxmlsec with XMLSEC_OPENSSL_100 compiling flag

### ISSUE THREAD

**Issue by serg666** [dnet/pyxmlsec#4]
Hi!
I try to use pyxmlsec library with xmldsig in my environment
In app.c I have found that some functions return values ONLY when OPENSSL >= 0.9.8
In my environment xmlsec1-openssl has build with XMLSEC_OPENSSL_100 flag
pkg-config xmlsec1-openssl --cflags
-DXMLSEC_CRYPTO=\"openssl\" -D__XMLSEC_FUNCTION__=__FUNCTION__ -DXMLSEC_NO_SIZE_T -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_XKMS=1 -DXMLSEC_DL_LIBLTDL=1 -DOPENSSL_LOAD_CONF -DXMLSEC_OPENSSL_100=1 -DXMLSEC_CRYPTO_OPENSSL=1 -I/usr/include/xmlsec1 -I/usr/include/libxml2

but in app.c I have found the following IF DEFINED

#if defined XMLSEC_CRYPTO_OPENSSL && defined XMLSEC_OPENSSL_098

So why I can't using pyxmlsec with such compiling flags?

**Comment by dnet** [comment]
I have no idea. I'm not the developer of pyxmlsec, I just put the source code to GitHub and applied a patch I found on the web to make it compile on Python 2.x where x > 4. I also haven't used pyxmlsec since 2012, so I don't even have any recent experience w.r.t using it, much less compiling it.

**Comment by serg666** [comment]
Due to source code (app.c) the extension (xmlsecmod) will properly compiled with XMLSEC_OPENSSL_098=1 compiler flag (define_macros)

From setup.py (line 133) I have found that these define_macros are retrieved from XMLSec1 pre-processor and compiler flags

But in my environment XMLSec1 pre-processor and compiler flags contain XMLSEC_OPENSSL_100=1 flag

Perhaps, If setup.py will use XMLSEC_OPENSSL_098=1 define_macros for all XMLSEC_OPENSSL_X.X.X compiling flag where X.X.X >= 098 it will solve the problem

**Comment by dnet** [comment]
It's good to hear that it works properly for you. Do you have an idea how it could be patched so that it works for versions before _and_ after 1.0.0?

**Comment by serg666** [comment]
I think xmlsecmod will work properly if it will compile with XMLSEC_OPENSSL_098=1 flag.

So, I think setup.py have to check XMLSEC_OPENSSL_XXX compiling flag and if XXX >= 0.9.8 it must use XMLSEC_OPENSSL_098

**Comment by dnet** [comment]
could you submit that as a pull request?
