### ISSUE TITLE
When installing, SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by isgallagher** [dnet/pyxmlsec#9]
Collecting pyxmlsec-next
  Downloading https://files.pythonhosted.org/packages/47/3b/c2c2337115fb1c490f4f8d8faa14139bf4a91d91ffe117b2e1a9f245d900/pyxmlsec-next-0.3.1.tar.gz (101kB)
    100% |████████████████████████████████| 102kB 416kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4lj4vahk/pyxmlsec-next/setup.py", line 49
        raise SystemExit, "PyXMLSec requires Python version 2.2 or above."
                        ^
    SyntaxError: invalid syntax

    ----------------------------------------

**Comment by dnet** [comment]
You're using Python 3, PyXMLSec supports only Python 2.
